### PR TITLE
envoy: upgrade to 1.23.1

### PR DESCRIPTION
**Pull request by calebdoxsey**
## Summary

Upgrade to envoy 1.23.0

## Related issues
- https://github.com/pomerium/internal/issues/931

## Checklist

- [ ] reference any related issues
- [ ] updated docs
- [ ] updated unit tests
- [ ] updated UPGRADING.md
- [ ] add appropriate tag (`improvement` / `bug` / etc)
- [x] ready for review

### CODE REVIEW

**Review by desimone — COMMENTED** [review]
LGTM pending @wasaga

**Comment by wasaga** [comment]
holding it off by a few days to let bugfixes in first.

**Comment by wasaga** [comment]
blocked by https://github.com/envoyproxy/envoy/issues/22261

**Comment by desimone** [comment]
- 2.3.1 Fixes this and can be merged. 

https://github.com/pomerium/pomerium/pull/3599

**Review by desimone — COMMENTED** [review]
Did the port allocation change?

**Review by wasaga — APPROVED** [review]

**Pull request merged**
